import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import {
    AlertCircle,
    ArrowRight,
    BarChart3,
    Bot,
    Brain,
    Check,
    CheckCircle,
    Copy,
    FileText,
    Lightbulb,
    Loader2,
    Plus,
    Sparkles,
    TrendingUp,
    Wand2,
    XCircle
} from 'lucide-react';
import React, { useCallback, useState } from 'react';
import { toast } from 'sonner';

interface NoteAIProps {
  note: any;
  onUpdateNote: (noteId: string, updates: any) => void;
}

const NoteAI: React.FC<NoteAIProps> = ({ note, onUpdateNote }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [aiResponse, setAiResponse] = useState('');
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [grammarIssues, setGrammarIssues] = useState<any[]>([]);
  const [spellingIssues, setSpellingIssues] = useState<any[]>([]);
  const [activeTab, setActiveTab] = useState('generate');
  const [selectedSuggestion, setSelectedSuggestion] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<any>(null);

  // AI Generation
  const generateContent = useCallback(async (type: string, customPrompt?: string) => {
    setIsGenerating(true);
    try {
      const finalPrompt = customPrompt || prompt;
      
      // Simulate AI API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      let generatedContent = '';
      switch (type) {
        case 'summarize':
          generatedContent = `Summary of "${note.title}":\n\nThis note contains ${note.content.split(' ').length} words covering key topics. The main points include:\n\n• Point 1\n• Point 2\n• Point 3\n\nKey insights and recommendations are provided throughout the content.`;
          break;
        case 'improve':
          generatedContent = `Improved version of your content:\n\n${note.content}\n\nEnhancements made:\n• Improved clarity and flow\n• Enhanced vocabulary\n• Better structure and organization\n• More engaging tone`;
          break;
        case 'expand':
          generatedContent = `Expanded content based on your note:\n\n${note.content}\n\nAdditional context and details:\n• Background information\n• Related concepts\n• Examples and case studies\n• Further reading suggestions`;
          break;
        case 'custom':
          generatedContent = `AI generated content based on: "${finalPrompt}"\n\nThis is a comprehensive response that addresses your specific request. The content is tailored to your needs and provides valuable insights and actionable recommendations.`;
          break;
        default:
          generatedContent = `AI generated content for: ${type}\n\nThis is placeholder content that would be generated by an AI model based on your note and the specific request.`;
      }
      
      setAiResponse(generatedContent);
      onUpdateNote(note.id, {
        aiGenerated: true,
        aiContent: generatedContent,
        aiPrompt: finalPrompt,
        aiGeneratedAt: new Date()
      });
      
      toast.success('AI content generated successfully');
    } catch (error) {
      toast.error('Failed to generate AI content');
    } finally {
      setIsGenerating(false);
    }
  }, [note, prompt, onUpdateNote]);

  // Grammar and Spell Check
  const analyzeText = useCallback(async () => {
    setIsAnalyzing(true);
    try {
      // Simulate analysis
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      const mockGrammarIssues = [
        { type: 'grammar', message: 'Consider using active voice', suggestion: 'Use active voice instead of passive', position: 45 },
        { type: 'grammar', message: 'Sentence structure could be improved', suggestion: 'Break into shorter sentences', position: 120 }
      ];
      
      const mockSpellingIssues = [
        { word: 'recieve', suggestion: 'receive', position: 67 },
        { word: 'occured', suggestion: 'occurred', position: 89 }
      ];
      
      setGrammarIssues(mockGrammarIssues);
      setSpellingIssues(mockSpellingIssues);
      
      setAnalysis({
        wordCount: note.content.split(' ').length,
        sentenceCount: note.content.split(/[.!?]+/).length - 1,
        paragraphCount: note.content.split('\n\n').length,
        readingTime: Math.ceil(note.content.split(' ').length / 200),
        complexity: 'Medium',
        tone: 'Professional',
        suggestions: [
          'Consider adding more specific examples',
          'Break up long paragraphs',
          'Add transition words for better flow'
        ]
      });
      
      toast.success('Text analysis completed');
    } catch (error) {
      toast.error('Failed to analyze text');
    } finally {
      setIsAnalyzing(false);
    }
  }, [note.content]);

  // Smart Suggestions
  const generateSuggestions = useCallback(async () => {
    try {
      // Simulate suggestions generation
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const mockSuggestions = [
        'Add a table of contents for better organization',
        'Include relevant statistics or data points',
        'Consider adding visual elements like charts or diagrams',
        'Break down complex concepts into simpler terms',
        'Add call-to-action statements',
        'Include real-world examples or case studies'
      ];
      
      setSuggestions(mockSuggestions);
      toast.success('Suggestions generated');
    } catch (error) {
      toast.error('Failed to generate suggestions');
    }
  }, []);

  // Apply suggestion
  const applySuggestion = useCallback((suggestion: string) => {
    setSelectedSuggestion(suggestion);
    // Here you would apply the suggestion to the note content
    toast.success('Suggestion applied');
  }, []);

  // Quick actions
  const quickActions = [
    { name: 'Summarize', action: () => generateContent('summarize'), icon: FileText },
    { name: 'Improve', action: () => generateContent('improve'), icon: Wand2 },
    { name: 'Expand', action: () => generateContent('expand'), icon: TrendingUp },
    { name: 'Analyze', action: analyzeText, icon: BarChart3 },
    { name: 'Suggest', action: generateSuggestions, icon: Lightbulb }
  ];

  return (
    <div className="h-full flex flex-col bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <div className="p-4 border-b bg-white dark:bg-gray-800">
        <div className="flex items-center space-x-2 mb-4">
          <Brain className="h-5 w-5 text-blue-600" />
          <h2 className="text-lg font-semibold">AI Assistant</h2>
          <Badge variant="secondary">Beta</Badge>
        </div>
        
        {/* Quick Actions */}
        <div className="flex flex-wrap gap-2">
          {quickActions.map((action) => (
            <Button
              key={action.name}
              variant="outline"
              size="sm"
              onClick={action.action}
              disabled={isGenerating || isAnalyzing}
            >
              <action.icon className="h-4 w-4 mr-2" />
              {action.name}
            </Button>
          ))}
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-auto">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="h-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="generate">Generate</TabsTrigger>
            <TabsTrigger value="analyze">Analyze</TabsTrigger>
            <TabsTrigger value="suggest">Suggest</TabsTrigger>
            <TabsTrigger value="chat">Chat</TabsTrigger>
          </TabsList>

          <TabsContent value="generate" className="p-4">
            <Card>
              <CardHeader>
                <CardTitle>Content Generation</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium">Custom Prompt</label>
                  <Textarea
                    placeholder="Describe what you want AI to generate..."
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    className="mt-1"
                    rows={3}
                  />
                </div>
                
                <Button
                  onClick={() => generateContent('custom')}
                  disabled={isGenerating || !prompt.trim()}
                  className="w-full"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Generate Content
                    </>
                  )}
                </Button>

                {aiResponse && (
                  <div className="mt-4">
                    <label className="text-sm font-medium">Generated Content</label>
                    <div className="mt-1 p-3 bg-blue-50 dark:bg-blue-900 rounded border">
                      <pre className="whitespace-pre-wrap text-sm">{aiResponse}</pre>
                    </div>
                    <div className="mt-2 flex space-x-2">
                      <Button size="sm" onClick={() => onUpdateNote(note.id, { content: note.content + '\n\n' + aiResponse })}>
                        <Plus className="h-4 w-4 mr-2" />
                        Add to Note
                      </Button>
                      <Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(aiResponse)}>
                        <Copy className="h-4 w-4 mr-2" />
                        Copy
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="analyze" className="p-4">
            <Card>
              <CardHeader>
                <CardTitle>Text Analysis</CardTitle>
              </CardHeader>
              <CardContent>
                <Button
                  onClick={analyzeText}
                  disabled={isAnalyzing}
                  className="w-full mb-4"
                >
                  {isAnalyzing ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    <>
                      <BarChart3 className="h-4 w-4 mr-2" />
                      Analyze Text
                    </>
                  )}
                </Button>

                {analysis && (
                  <div className="space-y-4">
                    {/* Statistics */}
                    <div className="grid grid-cols-2 gap-4">
                      <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded">
                        <div className="text-2xl font-bold">{analysis.wordCount}</div>
                        <div className="text-sm text-gray-500">Words</div>
                      </div>
                      <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded">
                        <div className="text-2xl font-bold">{analysis.readingTime}</div>
                        <div className="text-sm text-gray-500">Min Read</div>
                      </div>
                    </div>

                    {/* Issues */}
                    {(grammarIssues.length > 0 || spellingIssues.length > 0) && (
                      <div>
                        <h4 className="font-medium mb-2">Issues Found</h4>
                        {grammarIssues.map((issue, index) => (
                          <div key={index} className="flex items-start space-x-2 p-2 bg-yellow-50 dark:bg-yellow-900 rounded mb-2">
                            <AlertCircle className="h-4 w-4 text-yellow-600 mt-0.5" />
                            <div>
                              <p className="text-sm font-medium">{issue.message}</p>
                              <p className="text-xs text-gray-600">{issue.suggestion}</p>
                            </div>
                          </div>
                        ))}
                        {spellingIssues.map((issue, index) => (
                          <div key={index} className="flex items-start space-x-2 p-2 bg-red-50 dark:bg-red-900 rounded mb-2">
                            <XCircle className="h-4 w-4 text-red-600 mt-0.5" />
                            <div>
                              <p className="text-sm font-medium">Spelling: "{issue.word}"</p>
                              <p className="text-xs text-gray-600">Suggestion: "{issue.suggestion}"</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Suggestions */}
                    {analysis.suggestions && (
                      <div>
                        <h4 className="font-medium mb-2">Improvement Suggestions</h4>
                        <ul className="space-y-1">
                          {analysis.suggestions.map((suggestion, index) => (
                            <li key={index} className="flex items-start space-x-2">
                              <CheckCircle className="h-4 w-4 text-green-600 mt-0.5" />
                              <span className="text-sm">{suggestion}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="suggest" className="p-4">
            <Card>
              <CardHeader>
                <CardTitle>Smart Suggestions</CardTitle>
              </CardHeader>
              <CardContent>
                <Button
                  onClick={generateSuggestions}
                  className="w-full mb-4"
                >
                  <Lightbulb className="h-4 w-4 mr-2" />
                  Generate Suggestions
                </Button>

                {suggestions.length > 0 && (
                  <div className="space-y-2">
                    {suggestions.map((suggestion, index) => (
                      <div key={index} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-800 rounded">
                        <span className="text-sm">{suggestion}</span>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => applySuggestion(suggestion)}
                        >
                          <Check className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="chat" className="p-4">
            <Card>
              <CardHeader>
                <CardTitle>AI Chat</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex space-x-2">
                    <Input
                      placeholder="Ask AI about your note..."
                      className="flex-1"
                      onKeyPress={(e) => {
                        if (e.key === 'Enter') {
                          generateContent('custom', e.currentTarget.value);
                          e.currentTarget.value = '';
                        }
                      }}
                    />
                    <Button onClick={() => generateContent('custom', prompt)}>
                      <ArrowRight className="h-4 w-4" />
                    </Button>
                  </div>
                  
                  <div className="text-center text-gray-500 text-sm">
                    <Bot className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p>Ask me anything about your note content, structure, or writing style.</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default NoteAI; 